### ISSUE TITLE
Script Panel and ability to open/save scripts via UI.

### ISSUE THREAD

**Issue by Darwish8040** [NotDSF/PSUTools#1]
One of the biggest gripe about the Web UI is the fact that it doesn't have a script selector/panel and the process of copying and pasting scripts becomes tedious.

My suggestion is for the UI to have a scripts folder that shows all txt/lua files in the side panels of the UI, as well as ability to open & save scripts via the UI as well.

**Comment by NotDSF** [comment]
You can open scripts via file tab

I'll add save script in a future update

**Comment by topfragbro** [comment]
when are you gonna add save script
