### ISSUE TITLE
add an installer

### ISSUE THREAD

**Issue by nostopgmaming17** [NotDSF/PSUTools#2]
im not gonna download a 500 mb file especially with github slow download speed

**Comment by NotDSF** [comment]
Gonna try my best to do something about these sizes it's a pain for me as well

**Comment by nostopgmaming17** [comment]
alr ty

**Comment by NotDSF** [comment]
https://github.com/NotDSF/KrampusUI/releases/tag/beta-v1.0.2 fixed in new ver
