### ISSUE TITLE
add script tabs

### ISSUE THREAD

**Issue by overextending** [NotDSF/PSUTools#5]

**Comment by lloydish6420** [comment]
its pretty annoying to save your scripts as a text file all the time tbh

**Comment by womanburner** [comment]
add script sidebar**** read for scripts folder in krampus directory (not roui) and put scripts in there on the sidebar like literally every other executor in existence

**Comment by NotDSF** [comment]
Did synapse x have script tabs?

**Comment by ImInTheICU** [comment]
> Did synapse x have script tabs?

Yes?

**Comment by Darwish8040** [comment]
Add both script tabs AND script side panel then this will be lot more usable.
