### ISSUE TITLE
'please select a valid ro exec installation' with the new krampus loader

### ISSUE THREAD

**Issue by womanburner** [NotDSF/PSUTools#8]
with the updated krampus loader it doesnt recognise the directory as ro exec so basically this doesnt work at all rn

**Comment by RianakramPRO** [comment]
is this an virus

**Comment by NotDSF** [comment]
https://github.com/NotDSF/KrampusUI/releases/tag/beta-v1.0.2 fixed in new ver

**Comment by womanburner** [comment]
AMBATUKAMMMMM
